version: "3.9"
services:
  server:
    build: ./server
    container_name: visualogic-server
    ports:
      - "5000:5000"
    restart: unless-stopped

  client:
    build: ./client
    container_name: visualogic-client
    ports:
      - "3000:3000"
    depends_on:
      - server
    restart: unless-stopped
