version: '3.8'
services:
  server:
    build: ./server
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
    volumes:
      - ./server:/app
      - /app/node_modules
    command: npm run dev

  client:
    build: ./client
    ports:
      - "8080:80"
    depends_on:
      - server
    volumes:
      - ./client:/app
      - /app/node_modules
