name: Ultimate CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & Push Backend
        run: |
          docker build -t ${{ steps.login-ecr.outputs.registry }}/visualogic-backend:latest ./server
          docker push ${{ steps.login-ecr.outputs.registry }}/visualogic-backend:latest

      - name: Build & Push Frontend
        run: |
          docker build -t ${{ steps.login-ecr.outputs.registry }}/visualogic-frontend:latest ./client
          docker push ${{ steps.login-ecr.outputs.registry }}/visualogic-frontend:latest

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --region ap-south-1 --name visualogic-eks-cluster

      - name: Deploy to EKS
        run: |
          kubectl apply -f k8s/backend-deployment.yaml
          kubectl apply -f k8s/backend-service.yaml
          kubectl apply -f k8s/frontend-deployment.yaml
          kubectl apply -f k8s/frontend-service.yaml
          kubectl apply -f k8s/ingress.yaml
